name = "template"
version = "0.0.1"
description = "gleam template"
licences = ["MIT"]
repository = { type = "github", user = "spotdemo4", repo = "gleam-template" }

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
go_over = ">= 3.2.2 and < 4.0.0"
