name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "force"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

concurrency:
  group: release

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: spotdemo4/nix-init@53edf99ddf1116ee1a53e7312606e5d1399d37da # v1.25.1
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0
          shell: bump

      - name: Bump
        run: bumper
        env:
          FORCE: ${{ inputs.force }}
          PATHS: |-
            .github/README.md
            action.yaml
